trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  containerRegistry: 'votifyacr.azurecr.io'
  imageRepository: 'resultapp'
  tag: '$(Build.BuildId)'
  acrUsername: 'votifyacr'  # Can get via az acr credential show
  # acrPassword will be set as a secret variable in the pipeline UI

pool:
  name: 'Votingapp'

stages:
- stage: BuildAndPush
  displayName: Build and Push ARM64 Image
  jobs:
  - job: BuildPush
    displayName: Build & Push
    steps:

    # Install Docker
    - task: DockerInstaller@0
      displayName: Install Docker

    # Docker login using secret variable
    - script: |
        echo "Logging into Azure Container Registry..."
        echo $(acrPassword) | docker login $(containerRegistry) -u $(acrUsername) --password-stdin
      displayName: Docker Login to ACR

    # Setup QEMU for cross-platform build (ARM64)
    - script: |
        docker run --rm --privileged tonistiigi/binfmt --install all
      displayName: Setup QEMU for ARM64

    # Setup Buildx
    - script: |
        docker buildx create --name mybuilder --use || true
        docker buildx inspect --bootstrap
      displayName: Setup Docker Buildx

    # Build & Push ARM64 image
    - script: |
        export DOCKER_BUILDKIT=1
        docker buildx build \
          --platform linux/arm64 \
          -f $(Build.SourcesDirectory)/result/Dockerfile \
          -t $(containerRegistry)/$(imageRepository):$(tag) \
          -t $(containerRegistry)/$(imageRepository):latest \
          --push \
          $(Build.SourcesDirectory)/result
      displayName: Build & Push ARM64 Image
