trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  containerRegistry: 'votifyacr.azurecr.io'
  imageRepository: 'resultapp'
  tag: '$(Build.BuildId)'
  acrUsername: 'votifyacr'        # ACR username
  acrPassword: $(acrPassword)      # Secret variable in DevOps

pool:
  name: 'Votingapp'

stages:
- stage: BuildAndPush
  displayName: Build and Push ARM64 Image
  jobs:
  - job: BuildPush
    displayName: Build & Push
    steps:

    # Install Docker if not already present
    - task: DockerInstaller@0
      displayName: Install Docker

    # Docker login to ACR using username/password
    - script: |
        echo "Logging into ACR..."
        echo $(acrPassword) | docker login $(containerRegistry) -u $(acrUsername) --password-stdin
      displayName: Docker Login to ACR

    # Setup Buildx builder for ARM64
    - script: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        export DOCKER_BUILDKIT=1
        docker buildx create --name mybuilder --use || true
        docker buildx inspect --bootstrap
      displayName: Setup Buildx Builder

    # Build and push ARM64 image
    - script: |
        echo "Building and pushing ARM64 image..."
        docker buildx build \
          --platform linux/arm64 \
          -f $(Build.SourcesDirectory)/result/Dockerfile \
          -t $(containerRegistry)/$(imageRepository):$(tag) \
          -t $(containerRegistry)/$(imageRepository):latest \
          --push \
          $(Build.SourcesDirectory)/result
      displayName: Build & Push ARM64 Image
