trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'a5a1b2b0-3823-4d46-b405-a7aa63ecc2d5'
  imageRepository: 'resultapp'
  containerRegistry: 'votifyacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'Votingapp' 

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: 'votifyacr'
        repository: 'resultapp'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: |
          $(tag)
          latest   # <-- Add latest tag here

- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push image
    steps:
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'votifyacr'
        repository: 'resultapp'
        command: 'push'
        tags: |
          $(tag)
          latest   # <-- Push both tags
