trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  containerRegistry: 'votifyacr.azurecr.io'
  imageRepository: 'resultapp'
  tag: '$(Build.BuildId)'

pool:
  name: 'Votingapp'

stages:
- stage: BuildAndPush
  displayName: Build and Push ARM64 Image via ACR
  jobs:
  - job: BuildPush
    displayName: Build & Push
    steps:

    # Login to Azure
    - task: AzureCLI@2
      displayName: Login to Azure
      inputs:
        azureSubscription: 'votify-acr'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging into Azure..."
          az account set --subscription a6da4d80-5687-44ae-b032-172418adb940

    # Build and push ARM64 image using ACR Premium
    - task: AzureCLI@2
      displayName: Build & Push ARM64 Image via ACR
      inputs:
        azureSubscription: 'votify-acr'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Starting ACR build for ARM64 image..."
          az acr build \
            --registry votifyacr \
            --image $(imageRepository):$(tag) \
            --image $(imageRepository):latest \
            --platform linux/arm64 \
            ./result
