trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  # Azure Container Registry and image details
  dockerRegistryServiceConnection: 'a5a1b2b0-3823-4d46-b405-a7aa63ecc2d5'
  containerRegistry: 'votifyacr.azurecr.io'
  imageRepository: 'resultapp'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  displayName: Build and Push ARM64 Image
  jobs:
  - job: BuildPush
    displayName: Build & Push
    steps:

    # Install Docker if not already present
    - task: DockerInstaller@0
      displayName: Install Docker

    # Login to Azure
    - task: AzureCLI@2
      displayName: Login to Azure
      inputs:
        azureSubscription: 'votify-acr'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging into ACR..."
          az acr login --name votifyacr

    # Build and push ARM64 image using Docker Buildx
    - script: |
        echo "Enable BuildKit"
        export DOCKER_BUILDKIT=1

        echo "Create buildx builder (if not exists)"
        docker buildx create --use || true

        echo "Build and push ARM64 image to ACR"
        docker buildx build \
          --platform linux/arm64 \
          -f $(Build.SourcesDirectory)/result/Dockerfile \
          -t $(containerRegistry)/$(imageRepository):$(tag) \
          -t $(containerRegistry)/$(imageRepository):latest \
          --push \
          $(Build.SourcesDirectory)/result
      displayName: Build & Push ARM64 Image