trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  containerRegistry: 'votifyacr.azurecr.io'
  imageRepository: 'resultapp'
  tag: '$(Build.BuildId)'

pool:
  name: 'Votingapp'

stages:
- stage: BuildAndPush
  displayName: Build and Push ARM64 Image
  jobs:
  - job: BuildPush
    displayName: Build & Push
    steps:

    # Install Docker if not already present
    - task: DockerInstaller@0
      displayName: Install Docker

    # Login to Azure
    - task: AzureCLI@2
      displayName: Login to Azure
      inputs:
        azureSubscription: 'votify-acr'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging into Azure Container Registry..."
          az acr login --name votifyacr

    # Setup QEMU for ARM64 builds (needed for cross-platform builds)
    - script: |
        docker run --rm --privileged tonistiigi/binfmt --install all
      displayName: Setup QEMU for cross-platform builds

    # Setup Docker Buildx
    - script: |
        docker buildx create --name mybuilder --use || true
        docker buildx inspect --bootstrap
      displayName: Setup Docker Buildx

    # Build and push ARM64 image using Buildx
    - script: |
        docker buildx build \
          --platform linux/arm64, linux/amd64 \
          -f $(Build.SourcesDirectory)/result/Dockerfile \
          -t $(containerRegistry)/$(imageRepository):$(tag) \
          -t $(containerRegistry)/$(imageRepository):latest \
          --push \
          $(Build.SourcesDirectory)/result
      displayName: Build & Push ARM64 Image
